security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\User: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email # ou username, selon le champ utilisé pour l'authentification

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: app.security.authentication_success_handler
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        

    access_control:
       
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/inscrire-candidat, roles: PUBLIC_ACCESS }
        - { path: ^/api/inscrire-admin, roles: PUBLIC_ACCESS }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/formation, roles: ['ROLE_ADMIN'] }
        - { path: ^/api/postuler, roles: ROLE_CANDIDAT }
        - { path: ^/api/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
